name: 'Auto Assign'
on: 
  pull_request:
    types: [opened]

permissions:
  contents: write
  pull-requests: write

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: ".github/auto-assign-config.yml"